[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run test:db && npm run db:migrate || echo 'Migration failed, continuing...' && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING = "1"
CORS_ORIGIN = "https://on-demand-video-frontend-production.up.railway.app"

# Build configuration
[build.envs]
NODE_ENV = "production"
NIXPACKS_NODE_PACKAGE_MANAGER = "npm"
PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING = "1" 